name: autoapply
version: "0.4.1.3"
synopsis: Template Haskell to automatically pass values to functions
description: See readme.md
category: Template Haskell
maintainer: Joe Hermaszewski <if.it.fits.i.sits@monoid.al>
copyright: (c) 2020 Joe Hermaszewski
github: expipiplus1/autoapply
extra-source-files:
  - readme.md
  - default.nix
  - changelog.md
  - package.yaml

library:
  source-dirs: src
  dependencies:
    - base >= 4.12 && < 5
    - logict
    - mtl
    - template-haskell
    - th-desugar >= 1.12 && < 1.16
    - transformers
    - unification-fd

tests:
  doctests:
    main: Doctests.hs
    other-modules: Types
    source-dirs:
      - test
    dependencies:
      - base
      - doctest
      - autoapply

custom-setup:
 dependencies:
   - base
   - Cabal
   - cabal-doctest >= 1 && <1.1

ghc-options:
  - -Wall

default-extensions:
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - KindSignatures
  - LambdaCase
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TemplateHaskellQuotes
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - ViewPatterns
